apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: flipt-ebs-claim
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: flipt-ebs-sc
  resources:
    requests:
      storage: 4Gi