---  
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-ebs-claim
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: flipt-ebs-sc
  volumeMode: Filesystem
  resources:
    requests:
      storage: 10Gi